USE codeup_test_db;
DROP TABLE IF EXISTS albums;
CREATE TABLE albums (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    artist VARCHAR(50) NOT NULL DEFAULT 'UNKNOWN',
    name  VARCHAR(100) NOT NULL DEFAULT 'UNKNOWN',
    release_date INT(4) ZEROFILL,
    sales DECIMAL(11,2),
    genre VARCHAR(50) NOT NULL DEFAULT 'UNKNOWN',
    PRIMARY KEY (id),
    UNIQUE (name, artist)
);